//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTamer.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileHashCraft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete duplicate files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonDupDelete {
            get {
                return ResourceManager.GetString("ButtonDupDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonExecuteCommand {
            get {
                return ResourceManager.GetString("ButtonExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hash calculation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonHashCalc {
            get {
                return ResourceManager.GetString("ButtonHashCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hash Management に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonHashManagement {
            get {
                return ResourceManager.GetString("ButtonHashManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Same File Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonHashResult {
            get {
                return ResourceManager.GetString("ButtonHashResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonModify {
            get {
                return ResourceManager.GetString("ButtonModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return to standard settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonNormalSettings {
            get {
                return ResourceManager.GetString("ButtonNormalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonRemove {
            get {
                return ResourceManager.GetString("ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hash acquisition target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonTargetFilter {
            get {
                return ResourceManager.GetString("ButtonTargetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHA-256 (High security: More reliable, generally faster than MD5. Recommended as standard) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HashAlgorithm_SHA256 {
            get {
                return ResourceManager.GetString("HashAlgorithm_SHA256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHA-384 (High security: higher security strength than SHA-256, but slightly slower calculation) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HashAlgorithm_SHA384 {
            get {
                return ResourceManager.GetString("HashAlgorithm_SHA384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHA-512 (maximum security: very high security strength, but slow computation) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HashAlgorithm_SHA512 {
            get {
                return ResourceManager.GetString("HashAlgorithm_SHA512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelCommand {
            get {
                return ResourceManager.GetString("LabelCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelCurrentDirectory {
            get {
                return ResourceManager.GetString("LabelCurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Scanning : Dicrecotires に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelDirectoryCount {
            get {
                return ResourceManager.GetString("LabelDirectoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory Scanning...: Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelDirectoryScanning {
            get {
                return ResourceManager.GetString("LabelDirectoryScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For Advanced User に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExpert {
            get {
                return ResourceManager.GetString("LabelExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whether to delete empty directories or not に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExpert_EmptyDirDelete {
            get {
                return ResourceManager.GetString("LabelExpert_EmptyDirDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target hidden files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExpert_HiddenFiles {
            get {
                return ResourceManager.GetString("LabelExpert_HiddenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target read-only files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExpert_ReadOnlyFiles {
            get {
                return ResourceManager.GetString("LabelExpert_ReadOnlyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whether to delete files of size 0 or not に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExpert_ZeroSizeFileDelete {
            get {
                return ResourceManager.GetString("LabelExpert_ZeroSizeFileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifying file types by extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtention_FilterSetting {
            get {
                return ResourceManager.GetString("LabelExtention_FilterSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify files by file type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtention_GroupFilterSetting {
            get {
                return ResourceManager.GetString("LabelExtention_GroupFilterSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_Applications {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_Archives {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_Archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Document Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_Documents {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movie Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_Movies {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Have Extentions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_NoHaveExtentions {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_NoHaveExtentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ohter Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_OtherFiles {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_OtherFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Picture Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_Pictures {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_Registrations {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_Registrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_Sounds {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source Code Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelExtentionFiles_SourceCodes {
            get {
                return ResourceManager.GetString("LabelExtentionFiles_SourceCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Computing file hash. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelFileCalcing {
            get {
                return ResourceManager.GetString("LabelFileCalcing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Searching for the same file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelFileMatching {
            get {
                return ResourceManager.GetString("LabelFileMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finished. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelFinished {
            get {
                return ResourceManager.GetString("LabelFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelFontSizeString {
            get {
                return ResourceManager.GetString("LabelFontSizeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelFontString {
            get {
                return ResourceManager.GetString("LabelFontString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of files whose hashes need to be retrieved : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelHashCalcing_AllHashNeedToGetFilesCount {
            get {
                return ResourceManager.GetString("LabelHashCalcing_AllHashNeedToGetFilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total number of target files :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelHashCalcing_AllTargetFilesCount {
            get {
                return ResourceManager.GetString("LabelHashCalcing_AllTargetFilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of files whose hashes have been retrieved : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelHashCalcing_HashGotFileCount {
            get {
                return ResourceManager.GetString("LabelHashCalcing_HashGotFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hash acquisition status : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelHashCalcing_HashGotPercent {
            get {
                return ResourceManager.GetString("LabelHashCalcing_HashGotPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of identical files found : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelHashCalcing_MatchHashCount {
            get {
                return ResourceManager.GetString("LabelHashCalcing_MatchHashCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name of the file being processed: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelHashCalcing_ProcessingFileName {
            get {
                return ResourceManager.GetString("LabelHashCalcing_ProcessingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular Expression Search Criteria に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegex_Criteria {
            get {
                return ResourceManager.GetString("LabelRegex_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular Expression Search Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegex_Error {
            get {
                return ResourceManager.GetString("LabelRegex_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An alternation construct in a regular expression contains a comment. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_AlternationHasComment {
            get {
                return ResourceManager.GetString("LabelRegexError_AlternationHasComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An alternation in a regular expression has a malformed condition. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_AlternationHasMalformedCondition {
            get {
                return ResourceManager.GetString("LabelRegexError_AlternationHasMalformedCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An alternation construct in a regular expression contains a malformed reference. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_AlternationHasMalformedReference {
            get {
                return ResourceManager.GetString("LabelRegexError_AlternationHasMalformedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An alternation construct in a regular expression uses a named capture. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_AlternationHasNamedCapture {
            get {
                return ResourceManager.GetString("LabelRegexError_AlternationHasNamedCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An alternation in a regular expression has too many conditions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_AlternationHasTooManyConditions {
            get {
                return ResourceManager.GetString("LabelRegexError_AlternationHasTooManyConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An alternation construct in a regular expression contains an undefined reference. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_AlternationHasUndefinedReference {
            get {
                return ResourceManager.GetString("LabelRegexError_AlternationHasUndefinedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The group name of a captured group in a regular expression is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_CaptureGroupNameInvalid {
            get {
                return ResourceManager.GetString("LabelRegexError_CaptureGroupNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A regular expression defines a numbered subexpression named zero. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_CaptureGroupOfZero {
            get {
                return ResourceManager.GetString("LabelRegexError_CaptureGroupOfZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A character class in a regular expression with an exclusion group is not the last part of the character class. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_ExclusionGroupNotLast {
            get {
                return ResourceManager.GetString("LabelRegexError_ExclusionGroupNotLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A regular expression has a non-escaped left parenthesis, or misses a closing right parenthesis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_InsufficientClosingParentheses {
            get {
                return ResourceManager.GetString("LabelRegexError_InsufficientClosingParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A regular expression has a non-escaped right parenthesis, or misses an opening left parenthesis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_InsufficientOpeningParentheses {
            get {
                return ResourceManager.GetString("LabelRegexError_InsufficientOpeningParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A hexadecimal escape sequence in a regular expression does not have enough digits, or contains invalid digits. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_InsufficientOrInvalidHexDigits {
            get {
                return ResourceManager.GetString("LabelRegexError_InsufficientOrInvalidHexDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A grouping construct in a regular expression is invalid or malformed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_InvalidGroupingConstruct {
            get {
                return ResourceManager.GetString("LabelRegexError_InvalidGroupingConstruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A Unicode property escape in a regular expression is invalid or unknown. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_InvalidUnicodePropertyEscape {
            get {
                return ResourceManager.GetString("LabelRegexError_InvalidUnicodePropertyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A named reference in a regular expression is malformed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_MalformedNamedReference {
            get {
                return ResourceManager.GetString("LabelRegexError_MalformedNamedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A Unicode property escape is malformed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_MalformedUnicodePropertyEscape {
            get {
                return ResourceManager.GetString("LabelRegexError_MalformedUnicodePropertyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A control character in a regular expression is missing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_MissingControlCharacter {
            get {
                return ResourceManager.GetString("LabelRegexError_MissingControlCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeated quantifiers on another quantifier inside a regular expression are not grouped in parentheses. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_NestedQuantifiersNotParenthesized {
            get {
                return ResourceManager.GetString("LabelRegexError_NestedQuantifiersNotParenthesized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A quantifier in a regular expression is in a position where it cannot quantify anything, like at the beginning of a regular expression or in a group. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_QuantifierAfterNothing {
            get {
                return ResourceManager.GetString("LabelRegexError_QuantifierAfterNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A captured group or a quantifier in a regular expression is not within range, that is, it is larger than Int32.MaxValue. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_QuantifierOrCaptureGroupOutOfRange {
            get {
                return ResourceManager.GetString("LabelRegexError_QuantifierOrCaptureGroupOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A character class in a regular expression contains an inverse character range, like z-a instead of a-z. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_ReversedCharacterRange {
            get {
                return ResourceManager.GetString("LabelRegexError_ReversedCharacterRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A quantifier range in a regular expression is inverse, like {10,1} instead of {1,10}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_ReversedQuantifierRange {
            get {
                return ResourceManager.GetString("LabelRegexError_ReversedQuantifierRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A character-class in a regular expression contains a short-hand class that is not allowed inside a character class. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_ShorthandClassInCharacterRange {
            get {
                return ResourceManager.GetString("LabelRegexError_ShorthandClassInCharacterRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A used named reference in a regular expression is not defined. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_UndefinedNamedReference {
            get {
                return ResourceManager.GetString("LabelRegexError_UndefinedNamedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A used numbered reference in a regular expression is not defined. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_UndefinedNumberedReference {
            get {
                return ResourceManager.GetString("LabelRegexError_UndefinedNumberedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A regular expression ends with a non-escaped ending backslash. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_UnescapedEndingBackslash {
            get {
                return ResourceManager.GetString("LabelRegexError_UnescapedEndingBackslash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unknown regular expression parse error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_Unknown {
            get {
                return ResourceManager.GetString("LabelRegexError_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A control character in a regular expression is not recognized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_UnrecognizedControlCharacter {
            get {
                return ResourceManager.GetString("LabelRegexError_UnrecognizedControlCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An escape character or sequence in a regular expression is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_UnrecognizedEscape {
            get {
                return ResourceManager.GetString("LabelRegexError_UnrecognizedEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A unicode property in a regular expression is not recognized, or invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_UnrecognizedUnicodeProperty {
            get {
                return ResourceManager.GetString("LabelRegexError_UnrecognizedUnicodeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A regular expression has a non-escaped left square bracket, or misses a closing right square bracket. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_UnterminatedBracket {
            get {
                return ResourceManager.GetString("LabelRegexError_UnterminatedBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A comment in a regular expression is not terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelRegexError_UnterminatedComment {
            get {
                return ResourceManager.GetString("LabelRegexError_UnterminatedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   During internal file writing or other processing of found files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelSettings {
            get {
                return ResourceManager.GetString("LabelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of all files to get hash : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelShowTargetInfo_CountAllFilesGetHash {
            get {
                return ResourceManager.GetString("LabelShowTargetInfo_CountAllFilesGetHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of files for which a hash has already been obtained : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelShowTargetInfo_CountAlreadyGetHash {
            get {
                return ResourceManager.GetString("LabelShowTargetInfo_CountAlreadyGetHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of files to get hashes from filtered files : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelShowTargetInfo_CountFilteredGetHash {
            get {
                return ResourceManager.GetString("LabelShowTargetInfo_CountFilteredGetHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Algorithm for file hash calculation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelShowTargetInfo_HashAlgorithm {
            get {
                return ResourceManager.GetString("LabelShowTargetInfo_HashAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wildcard Search Criteria に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelWildcard_Criteria {
            get {
                return ResourceManager.GetString("LabelWildcard_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wildcard Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelWildcard_Error {
            get {
                return ResourceManager.GetString("LabelWildcard_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wildcard conditions that have already been registered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelWildcardError_AlreadyRegistered {
            get {
                return ResourceManager.GetString("LabelWildcardError_AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wildcard search criteria not entered に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelWildcardError_Empty {
            get {
                return ResourceManager.GetString("LabelWildcardError_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Characters not allowed in file names に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelWildcardError_NotAllowedCharacter {
            get {
                return ResourceManager.GetString("LabelWildcardError_NotAllowedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Too much use of &apos;*&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelWildcardError_TooManyAsterisk {
            get {
                return ResourceManager.GetString("LabelWildcardError_TooManyAsterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Modified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListViewDataModified {
            get {
                return ResourceManager.GetString("ListViewDataModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListViewName {
            get {
                return ResourceManager.GetString("ListViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListViewSize {
            get {
                return ResourceManager.GetString("ListViewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListViewType {
            get {
                return ResourceManager.GetString("ListViewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug(_D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuDebug {
            get {
                return ResourceManager.GetString("MenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Have Extention  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoHaveExtentions {
            get {
                return ResourceManager.GetString("NoHaveExtentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Caution) Advanced Settings(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabContentExpert {
            get {
                return ResourceManager.GetString("TabContentExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular Expression Settings(_R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabContentRegularExpression {
            get {
                return ResourceManager.GetString("TabContentRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Standard Settings(_N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabContentStarndard {
            get {
                return ResourceManager.GetString("TabContentStarndard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wildcard Settings(_W) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabContentWildCard {
            get {
                return ResourceManager.GetString("TabContentWildCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wildcard Filter Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleTargetFilterWindow {
            get {
                return ResourceManager.GetString("TitleTargetFilterWindow", resourceCulture);
            }
        }
    }
}
