//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexTamer.NET.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegexTamer.NET.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Replace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_Replace {
            get {
                return ResourceManager.GetString("Button_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace Test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_ReplaceTest {
            get {
                return ResourceManager.GetString("Button_ReplaceTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace Test Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button_ReplaceTestCancel {
            get {
                return ResourceManager.GetString("Button_ReplaceTestCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font change accept に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_FontAccept {
            get {
                return ResourceManager.GetString("Label_FontAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Sample に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_FontSample {
            get {
                return ResourceManager.GetString("Label_FontSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fonts and Font Size Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_FontSelectWindow {
            get {
                return ResourceManager.GetString("Label_FontSelectWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_FontSize {
            get {
                return ResourceManager.GetString("Label_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_FontString {
            get {
                return ResourceManager.GetString("Label_FontString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular Expression error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_RegexError {
            get {
                return ResourceManager.GetString("Label_RegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular Expression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_RegularExpression {
            get {
                return ResourceManager.GetString("Label_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_Replace {
            get {
                return ResourceManager.GetString("Label_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_TargetData {
            get {
                return ResourceManager.GetString("Label_TargetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RegexTamer.NET -  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_WindowTitle {
            get {
                return ResourceManager.GetString("Label_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An alternation construct in a regular expression contains a comment. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_AlternationHasComment {
            get {
                return ResourceManager.GetString("LabelRegexError_AlternationHasComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An alternation in a regular expression has a malformed condition. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_AlternationHasMalformedCondition {
            get {
                return ResourceManager.GetString("LabelRegexError_AlternationHasMalformedCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An alternation construct in a regular expression contains a malformed reference. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_AlternationHasMalformedReference {
            get {
                return ResourceManager.GetString("LabelRegexError_AlternationHasMalformedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An alternation construct in a regular expression uses a named capture. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_AlternationHasNamedCapture {
            get {
                return ResourceManager.GetString("LabelRegexError_AlternationHasNamedCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An alternation in a regular expression has too many conditions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_AlternationHasTooManyConditions {
            get {
                return ResourceManager.GetString("LabelRegexError_AlternationHasTooManyConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An alternation construct in a regular expression contains an undefined reference. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_AlternationHasUndefinedReference {
            get {
                return ResourceManager.GetString("LabelRegexError_AlternationHasUndefinedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The group name of a captured group in a regular expression is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_CaptureGroupNameInvalid {
            get {
                return ResourceManager.GetString("LabelRegexError_CaptureGroupNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A regular expression defines a numbered subexpression named zero. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_CaptureGroupOfZero {
            get {
                return ResourceManager.GetString("LabelRegexError_CaptureGroupOfZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular Expression search criteria not entered に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_Empty {
            get {
                return ResourceManager.GetString("LabelRegexError_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A character class in a regular expression with an exclusion group is not the last part of the character class. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_ExclusionGroupNotLast {
            get {
                return ResourceManager.GetString("LabelRegexError_ExclusionGroupNotLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A regular expression has a non-escaped left parenthesis, or misses a closing right parenthesis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_InsufficientClosingParentheses {
            get {
                return ResourceManager.GetString("LabelRegexError_InsufficientClosingParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A regular expression has a non-escaped right parenthesis, or misses an opening left parenthesis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_InsufficientOpeningParentheses {
            get {
                return ResourceManager.GetString("LabelRegexError_InsufficientOpeningParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A hexadecimal escape sequence in a regular expression does not have enough digits, or contains invalid digits. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_InsufficientOrInvalidHexDigits {
            get {
                return ResourceManager.GetString("LabelRegexError_InsufficientOrInvalidHexDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A grouping construct in a regular expression is invalid or malformed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_InvalidGroupingConstruct {
            get {
                return ResourceManager.GetString("LabelRegexError_InvalidGroupingConstruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A Unicode property escape in a regular expression is invalid or unknown. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_InvalidUnicodePropertyEscape {
            get {
                return ResourceManager.GetString("LabelRegexError_InvalidUnicodePropertyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A named reference in a regular expression is malformed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_MalformedNamedReference {
            get {
                return ResourceManager.GetString("LabelRegexError_MalformedNamedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A Unicode property escape is malformed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_MalformedUnicodePropertyEscape {
            get {
                return ResourceManager.GetString("LabelRegexError_MalformedUnicodePropertyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A control character in a regular expression is missing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_MissingControlCharacter {
            get {
                return ResourceManager.GetString("LabelRegexError_MissingControlCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeated quantifiers on another quantifier inside a regular expression are not grouped in parentheses. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_NestedQuantifiersNotParenthesized {
            get {
                return ResourceManager.GetString("LabelRegexError_NestedQuantifiersNotParenthesized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A quantifier in a regular expression is in a position where it cannot quantify anything, like at the beginning of a regular expression or in a group. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_QuantifierAfterNothing {
            get {
                return ResourceManager.GetString("LabelRegexError_QuantifierAfterNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A captured group or a quantifier in a regular expression is not within range, that is, it is larger than Int32.MaxValue. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_QuantifierOrCaptureGroupOutOfRange {
            get {
                return ResourceManager.GetString("LabelRegexError_QuantifierOrCaptureGroupOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A character class in a regular expression contains an inverse character range, like z-a instead of a-z. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_ReversedCharacterRange {
            get {
                return ResourceManager.GetString("LabelRegexError_ReversedCharacterRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A quantifier range in a regular expression is inverse, like {10,1} instead of {1,10}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_ReversedQuantifierRange {
            get {
                return ResourceManager.GetString("LabelRegexError_ReversedQuantifierRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A character-class in a regular expression contains a short-hand class that is not allowed inside a character class. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_ShorthandClassInCharacterRange {
            get {
                return ResourceManager.GetString("LabelRegexError_ShorthandClassInCharacterRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A used named reference in a regular expression is not defined. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_UndefinedNamedReference {
            get {
                return ResourceManager.GetString("LabelRegexError_UndefinedNamedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A used numbered reference in a regular expression is not defined. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_UndefinedNumberedReference {
            get {
                return ResourceManager.GetString("LabelRegexError_UndefinedNumberedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A regular expression ends with a non-escaped ending backslash. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_UnescapedEndingBackslash {
            get {
                return ResourceManager.GetString("LabelRegexError_UnescapedEndingBackslash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unknown regular expression parse error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_Unknown {
            get {
                return ResourceManager.GetString("LabelRegexError_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A control character in a regular expression is not recognized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_UnrecognizedControlCharacter {
            get {
                return ResourceManager.GetString("LabelRegexError_UnrecognizedControlCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An escape character or sequence in a regular expression is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_UnrecognizedEscape {
            get {
                return ResourceManager.GetString("LabelRegexError_UnrecognizedEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A unicode property in a regular expression is not recognized, or invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_UnrecognizedUnicodeProperty {
            get {
                return ResourceManager.GetString("LabelRegexError_UnrecognizedUnicodeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A regular expression has a non-escaped left square bracket, or misses a closing right square bracket. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_UnterminatedBracket {
            get {
                return ResourceManager.GetString("LabelRegexError_UnterminatedBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A comment in a regular expression is not terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelRegexError_UnterminatedComment {
            get {
                return ResourceManager.GetString("LabelRegexError_UnterminatedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuFont {
            get {
                return ResourceManager.GetString("MenuFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuOpenFile {
            get {
                return ResourceManager.GetString("MenuOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Save File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSaveFile {
            get {
                return ResourceManager.GetString("MenuSaveFile", resourceCulture);
            }
        }
    }
}
